import { useEffect, useMemo, useState, type CSSProperties, type ReactNode } from "react";
import { motion } from "framer-motion";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { loadDashboard } from "./api";
import type { DashboardData, Language, Manifest, SectionKey, SeriesRow } from "./types";

const TECH: Record<string, { key: string; en: string; es: string; color: string; family: string }> = {
  "Hidráulica": { key: "hydro", en: "Hydro", es: "Hidráulica", color: "#2E7DD7", family: "renewable" },
  "Eólica": { key: "wind", en: "Wind", es: "Eólica", color: "#20B785", family: "renewable" },
  "Solar fotovoltaica": { key: "solar_pv", en: "Solar PV", es: "Solar fotovoltaica", color: "#F0C94A", family: "renewable" },
  "Solar térmica": { key: "solar_thermal", en: "Solar thermal", es: "Solar térmica", color: "#E58A35", family: "renewable" },
  "Otras renovables": { key: "other_renewables", en: "Other renewables", es: "Otras renovables", color: "#89C05A", family: "renewable" },
  "Residuos renovables": { key: "renewable_waste", en: "Renewable waste", es: "Residuos renovables", color: "#68A95B", family: "renewable" },
  "Hidroeólica": { key: "hydro_wind", en: "Hydro-wind", es: "Hidroeólica", color: "#47B8B0", family: "renewable" },
  Nuclear: { key: "nuclear", en: "Nuclear", es: "Nuclear", color: "#9F85D8", family: "zero" },
  "Ciclo combinado": { key: "combined_cycle", en: "Combined cycle", es: "Ciclo combinado", color: "#E56857", family: "fossil" },
  "Cogeneración": { key: "cogeneration", en: "Cogeneration", es: "Cogeneración", color: "#C98772", family: "fossil" },
  "Carbón": { key: "coal", en: "Coal", es: "Carbón", color: "#7C8991", family: "fossil" },
  "Fuel + Gas": { key: "fuel_gas", en: "Fuel + gas", es: "Fuel + gas", color: "#A67363", family: "fossil" },
  "Motores diésel": { key: "diesel", en: "Diesel engines", es: "Motores diésel", color: "#9A6152", family: "fossil" },
  "Turbina de gas": { key: "gas_turbine", en: "Gas turbine", es: "Turbina de gas", color: "#B57861", family: "fossil" },
  "Turbina de vapor": { key: "steam_turbine", en: "Steam turbine", es: "Turbina de vapor", color: "#8E655A", family: "fossil" },
  "Residuos no renovables": { key: "nonrenewable_waste", en: "Non-renewable waste", es: "Residuos no renovables", color: "#69777D", family: "fossil" },
};

const C = {
  en: { strap: "Spain's electricity system, measured", generation: "Generation", interconnectors: "Interconnectors", coverage: "Coverage", marginal: "Marginal price", system: "System", generationTitle: "How Spain generates electricity", generationCopy: "Monthly generation by technology. National system; measured energy at source.", mix: "Generation mix", rolling: "12-month source trend", balance: "Generation and demand", shape: "The shape of a day", hourlyNeeded: "Hourly e·sios data is waiting for an API token", hourlyDetail: "No proxy or synthetic values are shown. Add ESIOS_TOKEN and run the source pipeline to activate this analysis.", interTitle: "Cross-border electricity flows", interCopy: "Signed measured exchanges: positive means imports, negative means exports.", coverageTitle: "When selected sources cover demand", coverageCopy: "Test a source set against a demand threshold for every observed hour.", marginalTitle: "Price-setting history and market context", marginalCopy: "Verified classifications end at the documented cutoff. Later prices and generation are context, not causality.", systemTitle: "Capacity and carbon context", systemCopy: "Installed power and the share of generation associated with CO₂-equivalent emissions.", installed: "Installed capacity", carbon: "Generation associated with CO₂-eq emissions", context: "OMIE price context", archive: "Verified marginal-technology archive", all: "All", renewables: "Renewables", lowCarbon: "Low carbon", fossil: "Fossil", from: "From", to: "To", sources: "Sources", updated: "Dataset generated", geography: "Geography", unavailable: "Not available", contextOnly: "Context only after 18 Mar 2025", error: "Validated public data could not be loaded.", retry: "Retry", noRows: "No validated observations are available for this module yet." },
  es: { strap: "El sistema eléctrico español, medido", generation: "Generación", interconnectors: "Interconexiones", coverage: "Cobertura", marginal: "Precio marginal", system: "Sistema", generationTitle: "Cómo genera electricidad España", generationCopy: "Generación mensual por tecnología. Sistema nacional; energía medida en origen.", mix: "Mix de generación", rolling: "Tendencia de fuentes a 12 meses", balance: "Generación y demanda", shape: "La forma de un día", hourlyNeeded: "Los datos horarios de e·sios esperan un token de API", hourlyDetail: "No se muestran aproximaciones ni datos sintéticos. Añade ESIOS_TOKEN y ejecuta el pipeline para activar este análisis.", interTitle: "Flujos eléctricos transfronterizos", interCopy: "Intercambios medidos con signo: positivo es importación y negativo, exportación.", coverageTitle: "Cuándo cubren la demanda las fuentes elegidas", coverageCopy: "Contrasta fuentes y un umbral de demanda para cada hora observada.", marginalTitle: "Historial de casación y contexto de mercado", marginalCopy: "La clasificación verificada termina en la fecha documentada. Después, precio y generación son contexto, no causalidad.", systemTitle: "Contexto de potencia y carbono", systemCopy: "Potencia instalada y proporción de generación asociada a emisiones de CO₂ equivalente.", installed: "Potencia instalada", carbon: "Generación asociada a emisiones de CO₂-eq", context: "Contexto de precio OMIE", archive: "Archivo verificado de tecnología marginal", all: "Todas", renewables: "Renovables", lowCarbon: "Bajas en carbono", fossil: "Fósiles", from: "Desde", to: "Hasta", sources: "Fuentes", updated: "Datos generados", geography: "Ámbito", unavailable: "No disponible", contextOnly: "Solo contexto desde el 18 mar 2025", error: "No se pudieron cargar los datos públicos validados.", retry: "Reintentar", noRows: "Todavía no hay observaciones validadas para este módulo." },
} as const;

const getLang = (): Language => new URLSearchParams(location.search).get("lang") === "es" ? "es" : "en";
const month = (value: string, lang: Language) => new Intl.DateTimeFormat(lang === "es" ? "es-ES" : "en-GB", { month: "short", year: "2-digit", timeZone: "UTC" }).format(new Date(`${value}-01T00:00:00Z`));
const compact = (value: number) => new Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 }).format(value);

function reshape(rows: SeriesRow[]) {
  const result = new Map<string, Record<string, string | number>>();
  rows.forEach((row) => { const meta = TECH[row.series]; if (!meta) return; const item = result.get(row.period) ?? { period: row.period, total: 0 }; item[meta.key] = row.value; item.total = Number(item.total) + row.value; result.set(row.period, item); });
  return [...result.values()].sort((a, b) => String(a.period).localeCompare(String(b.period)));
}
function rolling(rows: Array<Record<string, string | number>>, keys: string[]) { return rows.map((row, index) => { const win = rows.slice(Math.max(0, index - 11), index + 1); const out: Record<string, string | number> = { period: row.period }; keys.forEach((key) => out[key] = win.reduce((sum, item) => sum + Number(item[key] ?? 0), 0) / win.length); return out; }); }
function Empty({ title, copy }: { title: string; copy: string }) { return <div className="empty"><b>!</b><div><strong>{title}</strong><p>{copy}</p></div></div>; }
function Panel({ code, title, children, wide }: { code: string; title: string; children: ReactNode; wide?: boolean }) { return <motion.section className={`panel ${wide ? "wide" : ""}`} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><header><span>{code}</span><h2>{title}</h2></header>{children}</motion.section>; }

export default function App() {
  const [lang, setLang] = useState<Language>(getLang); const [section, setSection] = useState<SectionKey>("generation");
  const [data, setData] = useState<DashboardData | null>(null); const [manifest, setManifest] = useState<Manifest | null>(null); const [error, setError] = useState(""); const [attempt, setAttempt] = useState(0);
  const [family, setFamily] = useState("all"); const [from, setFrom] = useState("2019-01"); const [to, setTo] = useState("2026-12"); const t = C[lang];
  useEffect(() => { loadDashboard().then(({ dashboard, manifest: m }) => { setData(dashboard); setManifest(m); setFrom(m.coverage.monthly_start ?? "2019-01"); setTo(m.coverage.monthly_end ?? "2026-12"); }).catch((e) => setError(String(e))); }, [attempt]);
  const setLanguage = (next: Language) => { setLang(next); const url = new URL(location.href); next === "es" ? url.searchParams.set("lang", "es") : url.searchParams.delete("lang"); history.replaceState({}, "", url); document.documentElement.lang = next; };
  const allTech = useMemo(() => Object.values(TECH), []); const selected = allTech.filter((x) => family === "all" || (family === "low" ? ["renewable", "zero"].includes(x.family) : x.family === family)); const keys = selected.map((x) => x.key);
  const generation = useMemo(() => data ? reshape(data.generation).filter((x) => String(x.period) >= from && String(x.period) <= to) : [], [data, from, to]);
  const trend = useMemo(() => rolling(generation, keys), [generation, keys.join("|")]); const demandMap = new Map((data?.demand ?? []).filter((x) => x.series === "Demanda").map((x) => [x.period, x.value])); const balance = generation.map((x) => ({ period: x.period, generation: x.total, demand: demandMap.get(String(x.period)) }));
  const latest = data?.capacity.reduce((a, x) => x.period > a ? x.period : a, "") ?? ""; const capacity = (data?.capacity ?? []).filter((x) => x.period === latest && TECH[x.series]).sort((a, b) => b.value - a.value); const maxCap = Math.max(1, ...capacity.map((x) => x.value)); const carbon = (data?.emissions_context ?? []).filter((x) => x.series === "Con emisiones de CO2 eq.");
  const titles: Record<SectionKey, [string, string]> = { generation: [t.generationTitle, t.generationCopy], interconnectors: [t.interTitle, t.interCopy], coverage: [t.coverageTitle, t.coverageCopy], marginal: [t.marginalTitle, t.marginalCopy], system: [t.systemTitle, t.systemCopy] };
  const nav: Array<[SectionKey, string]> = [["generation", t.generation], ["interconnectors", t.interconnectors], ["coverage", t.coverage], ["marginal", t.marginal], ["system", t.system]]; const axis = { stroke: "#5D7481", fontSize: 11 }; const tip = { background: "#0C1824", border: "1px solid #29414E", borderRadius: 2, color: "#E8EEF0" };
  if (error) return <main className="fatal"><p className="kicker">DATA / ERROR</p><h1>{t.error}</h1><code>{error}</code><button onClick={() => { setError(""); setAttempt((x) => x + 1); }}>{t.retry}</button></main>;
  if (!data || !manifest) return <main className="loading"><span/><p>LOADING VERIFIED DATA</p></main>;
  return <div className="shell"><header className="topbar"><a className="identity" href="https://danielalmazan.com"><strong>REE Dashboard</strong><span>{t.strap}</span></a><nav>{nav.map(([key, label]) => <button key={key} className={section === key ? "active" : ""} onClick={() => setSection(key)}>{label}</button>)}</nav><div className="language"><button className={lang === "en" ? "active" : ""} onClick={() => setLanguage("en")}>EN</button><button className={lang === "es" ? "active" : ""} onClick={() => setLanguage("es")}>ES</button></div></header><main>
    <section className="section-head"><div><p className="kicker">SPAIN / ELECTRICITY / VERIFIED DATA</p><h1>{titles[section][0]}</h1><p>{titles[section][1]}</p></div><dl><div><dt>{t.updated}</dt><dd>{new Date(data.generated_at).toLocaleString(lang === "es" ? "es-ES" : "en-GB")}</dd></div><div><dt>{t.geography}</dt><dd>{data.geography.generation}</dd></div></dl></section>
    {section === "generation" && <><div className="controls"><div className="segments">{[["all", t.all], ["renewable", t.renewables], ["low", t.lowCarbon], ["fossil", t.fossil]].map(([v, label]) => <button className={family === v ? "active" : ""} onClick={() => setFamily(v)} key={v}>{label}</button>)}</div><label>{t.from}<input type="month" value={from} max={to} onChange={(e) => setFrom(e.target.value)}/></label><label>{t.to}<input type="month" value={to} min={from} onChange={(e) => setTo(e.target.value)}/></label></div>
      <Panel code="01 / MIX" title={t.mix} wide><div className="legend">{selected.map((x) => <span key={x.key}><i style={{ "--series": x.color } as CSSProperties}/>{x[lang]}</span>)}</div><ResponsiveContainer width="100%" height={410}><AreaChart data={generation}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(v) => month(v, lang)} {...axis}/><YAxis tickFormatter={compact} {...axis} width={68}/><Tooltip contentStyle={tip} formatter={(v: number) => [`${v.toLocaleString()} GWh`]}/>{selected.map((x) => <Area key={x.key} dataKey={x.key} stackId="mix" stroke={x.color} fill={x.color} fillOpacity={.88}/>)}</AreaChart></ResponsiveContainer></Panel>
      <div className="two"><Panel code="02 / TREND" title={t.rolling}><ResponsiveContainer width="100%" height={270}><LineChart data={trend}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(v) => month(v, lang)} {...axis}/><YAxis tickFormatter={compact} {...axis} width={55}/><Tooltip contentStyle={tip}/>{selected.slice(0, 7).map((x) => <Line key={x.key} dataKey={x.key} stroke={x.color} dot={false} strokeWidth={2}/>)}</LineChart></ResponsiveContainer></Panel><Panel code="03 / BALANCE" title={t.balance}><ResponsiveContainer width="100%" height={270}><LineChart data={balance}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(v) => month(v, lang)} {...axis}/><YAxis tickFormatter={compact} {...axis} width={55}/><Tooltip contentStyle={tip}/><Line dataKey="generation" stroke="#9EF01A" dot={false} strokeWidth={2}/><Line dataKey="demand" stroke="#E8EEF0" dot={false}/></LineChart></ResponsiveContainer></Panel></div><Panel code="04 / HOURLY" title={t.shape} wide><Empty title={t.hourlyNeeded} copy={t.hourlyDetail}/></Panel></>}
    {section === "interconnectors" && <Panel code="01 / BORDERS" title={t.interTitle} wide>{data.exchanges.length ? <ResponsiveContainer width="100%" height={400}><BarChart data={data.exchanges}><ReferenceLine y={0} stroke="#E8EEF0"/><Bar dataKey="value_gwh" fill="#9EF01A"/></BarChart></ResponsiveContainer> : <Empty title={t.hourlyNeeded} copy={t.hourlyDetail}/>}</Panel>}
    {section === "coverage" && <Panel code="01 / THRESHOLD" title={t.coverageTitle} wide><Empty title={t.hourlyNeeded} copy={t.hourlyDetail}/></Panel>}
    {section === "marginal" && <div className="two"><Panel code="01 / VERIFIED" title={t.archive}><div className="cutoff"><strong>18 MAR 2025</strong><span>{t.contextOnly}</span></div><Empty title={t.unavailable} copy={t.noRows}/></Panel><Panel code="02 / CONTEXT" title={t.context}><div className="flag">{t.contextOnly}</div>{data.omie_prices.length ? <ResponsiveContainer width="100%" height={300}><LineChart data={data.omie_prices}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(v) => month(v, lang)} {...axis}/><YAxis {...axis} width={55}/><Tooltip contentStyle={tip} formatter={(v: number) => [`€${v.toFixed(2)}/MWh`]}/><Line dataKey="price_es_eur_mwh" stroke="#9EF01A" dot={false} strokeWidth={2.5}/></LineChart></ResponsiveContainer> : <Empty title={t.unavailable} copy={t.noRows}/>}</Panel></div>}
    {section === "system" && <div className="two"><Panel code="01 / MW" title={t.installed}><div className="capacity">{capacity.slice(0, 12).map((row) => { const x = TECH[row.series]; return <div key={row.series}><span>{x[lang]}</span><i><b style={{ width: `${row.value / maxCap * 100}%`, background: x.color }}/></i><strong>{Math.round(row.value).toLocaleString()} MW</strong></div>; })}</div></Panel><Panel code="02 / CO₂-EQ" title={t.carbon}><ResponsiveContainer width="100%" height={360}><LineChart data={carbon}><CartesianGrid stroke="#203541" vertical={false}/><XAxis dataKey="period" tickFormatter={(v) => month(v, lang)} {...axis}/><YAxis domain={[0, 100]} {...axis} unit="%"/><Tooltip contentStyle={tip} formatter={(v: number) => [`${v.toFixed(1)}%`]}/><Line dataKey="share" stroke="#E56857" dot={false} strokeWidth={2.5}/></LineChart></ResponsiveContainer></Panel></div>}
    <footer><p className="kicker">{t.sources}</p>{data.sources.map((s) => <a href={s.url} key={s.key}>{s.key}<span>{s.last_update ? new Date(s.last_update).toLocaleDateString() : "—"}</span></a>)}</footer>
  </main></div>;
}
